### PR TITLE
Ensure we always set content_type of "application/json"

### PR DESCRIPTION
**Pull request by bdunne**
Fixes error:
unsupported media type "application/x-www-form-urlencoded" in request

https://bugzilla.redhat.com/show_bug.cgi?id=1348500

### CODE REVIEW

**Comment by bdunne** [comment]
@syncrou @gmcculloug Please review.

It doesn't look easy to add tests for this right now since it's embedded in Faraday.

**Comment by syncrou** [comment]
@bdunne 👍 LGTM

**Comment by gmcculloug** [comment]
@bdunne The change makes sense but do you know why it is needed?

From [faraday_middleware#dependencies](https://github.com/lostisland/faraday_middleware#dependencies)
`FaradayMiddleware::EncodeJson & FaradayMiddleware::ParseJson: "json" for ruby older than 1.9`

**Comment by bdunne** [comment]
@gmcculloug I'm not sure if that comment only applies to the `ParseJson` part.

**Comment by gmcculloug** [comment]
Got it, thanks.

**Pull request merged**
