### PR TITLE
Survey spec

### PR DESCRIPTION
**Pull request by syncrou**

### CODE REVIEW

**Comment by syncrou** [comment]
@bdunne - I redid the validation process - I found I needed it to work dynamically with the survey_specs - so the survey spec update process will be dependent on this PR.

**Comment by bdunne** [comment]
@syncrou Can you split this into a couple of PRs?  Gemspec changes, whitespace, leaving just the survey related work here?

**Comment by syncrou** [comment]
@bdunne - Yes I'll get that out in the morning.

**Comment by bdunne** [comment]
This validation logic seems complicated, maybe I don't understand all of the use cases.  I would expect `validate_json` to return a valid JSON string or raise.

The only caller that I am aware of right now is `extra = JSONValues.new(vars).extra_vars` in `JobTemplate.launch`

I think it would be a lot simpler to do something like:
```ruby
extra = Validation.validate_json(vars['extra_vars'])

module AnsibleTowerClient
  module Validation
    def self.validate_json(text)
      JSON.parse(text)
      text
    rescue JSON::ParserError => e
      raise InvalidJSON.new(self, e)
    end

    def self.validate_yaml(text)
      YAML.safe_parse(text)
      text
    rescue YAML::ParserError => e
      raise InvalidYAML.new(self, e)
    end
  end
end
```

**Pull request closed without merging**
